import Link from "next/link"
import { createClient } from "@/lib/supabase/server"
import { GalleryGrid } from "@/components/gallery-grid"
import { Nav } from "@/components/nav"
import { Footer } from "@/components/footer"
import { CommandPalette } from "@/components/command-palette"
import { LIBRARIES } from "@/lib/stack-data"
import type { Theme } from "@/lib/themes"

export const metadata = {
  title: "Gallery — Prism",
  description: "Browse stacks generated by the Prism community.",
}

export const revalidate = 30

type GalleryRow = {
  id: string
  prompt: string
  vibe: string
  audience: string
  performance: string
  headline: string
  rationale: string | null
  stack_ids: string[]
  theme: Theme
  impact_score: number
  perf_budget: number
  views: number
  likes: number
  created_at: string
}

export default async function GalleryPage() {
  const supabase = await createClient()
  const { data, error } = await supabase
    .from("stacks")
    .select(
      "id, prompt, vibe, audience, performance, headline, rationale, stack_ids, theme, impact_score, perf_budget, views, likes, created_at"
    )
    .order("created_at", { ascending: false })
    .limit(60)

  if (error) {
    console.error("[v0] gallery error", error)
  }

  const stacks: GalleryRow[] = (data as GalleryRow[]) ?? []
  const libMap = Object.fromEntries(LIBRARIES.map((l) => [l.id, l]))

  return (
    <main className="relative">
      <Nav />

      <section className="relative pt-32 pb-12 md:pt-40 md:pb-16">
        <div className="mx-auto max-w-7xl px-6">
          <div className="flex items-center gap-3 font-mono text-xs uppercase tracking-[0.25em] text-muted-foreground">
            <span className="text-primary">G</span>
            <span className="h-px w-8 bg-border" />
            <span>Public gallery</span>
          </div>
          <h1 className="mt-4 font-display text-6xl md:text-8xl tracking-[-0.04em] leading-[0.92] text-balance">
            Stacks{" "}
            <em className="italic text-muted-foreground">
              composed
              <br />
              in the wild.
            </em>
          </h1>
          <p className="mt-6 max-w-xl text-muted-foreground text-lg text-pretty">
            Briefs in. Stacks out. Each card is a real generation — tap one to apply its theme to
            the page, or open the full breakdown.
          </p>

          <div className="mt-8 flex items-center gap-4 text-xs text-muted-foreground">
            <Link href="/" className="font-mono uppercase tracking-wider hover:text-foreground transition" data-cursor="hover">
              ← Back to studio
            </Link>
            <span className="font-mono uppercase tracking-wider">
              {stacks.length} {stacks.length === 1 ? "stack" : "stacks"}
            </span>
          </div>
        </div>
      </section>

      <section className="relative pb-24">
        <div className="mx-auto max-w-7xl px-6">
          {stacks.length === 0 ? (
            <div className="rounded-lg border border-dashed border-border p-12 text-center">
              <p className="font-display text-3xl tracking-tight">
                No stacks yet. <em className="italic text-muted-foreground">Be the first.</em>
              </p>
              <p className="mt-3 text-muted-foreground">
                Compose a stack on the studio page and click <strong>Save to gallery</strong>.
              </p>
              <Link
                href="/#generator"
                className="mt-6 inline-flex items-center gap-2 rounded-full bg-primary px-5 py-2.5 text-sm font-medium text-primary-foreground"
              >
                Compose a stack →
              </Link>
            </div>
          ) : (
            <GalleryGrid
              stacks={stacks.map((s) => ({
                id: s.id,
                headline: s.headline,
                prompt: s.prompt,
                vibe: s.vibe,
                impactScore: s.impact_score,
                perfBudget: s.perf_budget,
                likes: s.likes,
                theme: s.theme,
                stackNames: (s.stack_ids ?? [])
                  .map((id) => libMap[id]?.name)
                  .filter(Boolean) as string[],
                createdAt: s.created_at,
              }))}
            />
          )}
        </div>
      </section>

      <Footer />
      <CommandPalette />
    </main>
  )
}
