import { Suspense } from "react"
import type { Metadata } from "next"
import Link from "next/link"
import { createClient } from "@/lib/supabase/server"
import { GalleryFeed } from "@/components/gallery-feed"
import { Nav } from "@/components/nav"
import { Footer } from "@/components/footer"
import { CommandPalette } from "@/components/command-palette"
import { JsonLd, breadcrumbList } from "@/components/json-ld"
import { LIBRARIES } from "@/lib/stack-data"
import type { Theme } from "@/lib/themes"
import type { GalleryItem } from "@/components/gallery-grid"
import { SITE_URL } from "@/lib/site"

export const metadata: Metadata = {
  title: "Gallery — Stacks composed in the wild",
  description:
    "Browse trending and brand-new stacks generated by the UXC community. Filter by vibe, library, or fuzzy-search by brief.",
  alternates: { canonical: "/gallery" },
  openGraph: {
    title: "UXC Gallery",
    description: "Browse trending and brand-new stacks generated by the UXC community.",
    type: "website",
    url: `${SITE_URL}/gallery`,
  },
}

export const revalidate = 30

type GalleryRow = {
  id: string
  prompt: string
  vibe: string
  audience: string
  performance: string
  headline: string
  rationale: string | null
  stack_ids: string[]
  theme: Theme
  impact_score: number
  perf_budget: number
  views: number
  likes: number
  created_at: string
  trending_score?: number
}

function rowsToItems(rows: GalleryRow[]): GalleryItem[] {
  const libMap = Object.fromEntries(LIBRARIES.map((l) => [l.id, l]))
  return rows.map((s) => ({
    id: s.id,
    headline: s.headline,
    prompt: s.prompt,
    vibe: s.vibe,
    impactScore: s.impact_score,
    perfBudget: s.perf_budget,
    likes: s.likes,
    theme: s.theme,
    stackNames: (s.stack_ids ?? [])
      .map((id) => libMap[id]?.name)
      .filter(Boolean) as string[],
    createdAt: s.created_at,
  }))
}

export default async function GalleryPage() {
  const supabase = await createClient()

  const [{ data: trendingRows }, { data: newestRows }, { data: allRows }] =
    await Promise.all([
      supabase
        .from("stacks_trending")
        .select(
          "id, prompt, vibe, audience, performance, headline, rationale, stack_ids, theme, impact_score, perf_budget, views, likes, created_at, trending_score",
        )
        .order("trending_score", { ascending: false })
        .limit(60),
      supabase
        .from("stacks")
        .select(
          "id, prompt, vibe, audience, performance, headline, rationale, stack_ids, theme, impact_score, perf_budget, views, likes, created_at",
        )
        .eq("published", true)
        .order("created_at", { ascending: false })
        .limit(60),
      supabase
        .from("stacks")
        .select(
          "id, prompt, vibe, audience, performance, headline, rationale, stack_ids, theme, impact_score, perf_budget, views, likes, created_at",
        )
        .eq("published", true)
        .order("likes", { ascending: false })
        .limit(60),
    ])

  const trending = rowsToItems((trendingRows as GalleryRow[]) ?? [])
  const newest = rowsToItems((newestRows as GalleryRow[]) ?? [])
  const allTime = rowsToItems((allRows as GalleryRow[]) ?? [])

  return (
    <main className="relative">
      <Nav />

      <JsonLd
        data={[
          breadcrumbList(SITE_URL, [
            { name: "Home", path: "/" },
            { name: "Gallery", path: "/gallery" },
          ]),
          {
            "@context": "https://schema.org",
            "@type": "CollectionPage",
            name: "UXC Gallery",
            url: `${SITE_URL}/gallery`,
            description: "Stacks composed by the UXC community.",
          },
        ]}
      />

      <section className="relative pt-32 pb-12 md:pt-40 md:pb-16">
        <div className="mx-auto max-w-7xl px-6">
          <div className="flex items-center gap-3 font-mono text-xs uppercase tracking-[0.25em] text-muted-foreground">
            <span className="text-primary">G</span>
            <span className="h-px w-8 bg-border" />
            <span>Public gallery</span>
          </div>
          <h1 className="mt-4 font-display text-6xl md:text-8xl tracking-[-0.04em] leading-[0.92] text-balance">
            Stacks{" "}
            <em className="italic text-muted-foreground">
              composed
              <br />
              in the wild.
            </em>
          </h1>
          <p className="mt-6 max-w-xl text-muted-foreground text-lg text-pretty">
            Briefs in. Stacks out. Each card is a real generation. Tap a card to apply its theme to
            the page, or open the full breakdown.
          </p>

          <div className="mt-8 flex items-center gap-4 text-xs text-muted-foreground">
            <Link
              href="/"
              className="font-mono uppercase tracking-wider hover:text-foreground transition"
              data-cursor="hover"
            >
              ← Back to studio
            </Link>
          </div>
        </div>
      </section>

      <section className="relative pb-24">
        <div className="mx-auto max-w-7xl px-6">
          {trending.length === 0 && newest.length === 0 ? (
            <div className="rounded-lg border border-dashed border-border p-12 text-center">
              <p className="font-display text-3xl tracking-tight">
                No stacks yet. <em className="italic text-muted-foreground">Be the first.</em>
              </p>
              <p className="mt-3 text-muted-foreground">
                Compose a stack on the studio page and click <strong>Save to gallery</strong>.
              </p>
              <Link
                href="/#generator"
                className="mt-6 inline-flex items-center gap-2 rounded-full bg-primary px-5 py-2.5 text-sm font-medium text-primary-foreground"
              >
                Compose a stack →
              </Link>
            </div>
          ) : (
            <Suspense
              fallback={
                <div className="h-32 animate-pulse rounded-lg border border-dashed border-border" />
              }
            >
              <GalleryFeed
                trending={trending}
                newest={newest}
                allTime={allTime}
              />
            </Suspense>
          )}
        </div>
      </section>

      <Footer />
      <CommandPalette />
    </main>
  )
}
